### ISSUE TITLE
Building db

### ISSUE THREAD

**Issue by ilyarudziak** [WizaXxX/docker_fresh#14]
![2020-06-15_17-40-56](https://user-images.githubusercontent.com/18754334/84671084-9a94fb00-af2f-11ea-9c45-09401d6b99fe.png)

Добрый день. Подскажите,  с чем может быть связано?

**Comment by WizaXxX** [comment]
Проверьте пожалуйста, поправил ссылку, теперь должно работать

**Comment by WizaXxX** [comment]
Проверил, сборка образа прошла корректно.

**Comment by ilyarudziak** [comment]
Добрый день. Прямо сейчас  разворачивают стенд для тестирования).
Такой вопрос, стенд нужно сразу установить а потом стартовать?

**Comment by WizaXxX** [comment]
Сначала выполняется формирование образом, а далее запуск.
Образы формируются запуском скрипта install.py и после запускается скрипт start.py с параметрами -new и -h

**Comment by ilyarudziak** [comment]
Понял, спасибо. Еще такой вопрос. А есть ли возможность указать как нибудь сервер лицензирования? (поднятый сервер на другом ПК)

**Comment by WizaXxX** [comment]
В документации раздел Лицензирование. 
Можно прописать в файле nethasp.ini адрес сервера лицензирования. Но это касается только клиентских лицензий.

**Comment by ilyarudziak** [comment]
> В документации раздел Лицензирование.
> Можно прописать в файле nethasp.ini адрес сервера лицензирования. Но это касается только клиентских лицензий.

Да. Тут нужно добавлять требования назначения функциональности.

Тут бы скрипт разделить, установить кластер, затем например руками настроить корректно кластер серверов, а затем уже продолжить выполнение.
Сейчас получается что если нет лицензий, базы (cf) никак не загрузятся (я про скрипт)

**Comment by WizaXxX** [comment]
Смысл скрипта сделать максимально быстро и просто. Чем больше скриптов запускать тем хуже:) 
Лицензии можно так делать: 

1. Запускаем install.py
2. Настраиваем лицензирование
3. Запускам start.py 

Для настройки лицензирования не нужен еще кластер

**Comment by ilyarudziak** [comment]
У меня просто есть в сети Сервер(на нем поднят сервер 1с и активированы лицензии)  - обычный выделенный сервер лицензирования (активированы программные клиентские и серверные лицензии).
Так я вот хочу в этот докер пропихнуть мой сервер (Добавить его в кластер и прописать соответствующие ТНФ). 
На сколько я понял после  install.py создаются директории и прочее, а чтобы собрать кластер нужно чтобы сервер 1С был запущен.
А может мне 2 раза запустить  start.py ? там при первом запуске он ругается на лицензии когда пытается базы загрузить, но после Информационного окна сервер работает в принципе он его не выключает
