### ISSUE TITLE
Подключение сервера 1С вне докера в качестве сервера лицензирования

### ISSUE THREAD

**Issue by WizaXxX** [WizaXxX/docker_fresh#15]
У меня просто есть в сети Сервер(на нем поднят сервер 1с и активированы лицензии)  - обычный выделенный сервер лицензирования (активированы программные клиентские и серверные лицензии).
Так я вот хочу в этот докер пропихнуть мой сервер (Добавить его в кластер и прописать соответствующие ТНФ). 
На сколько я понял после  install.py создаются директории и прочее, а чтобы собрать кластер нужно чтобы сервер 1С был запущен.
А может мне 2 раза запустить  start.py ? там при первом запуске он ругается на лицензии когда пытается базы загрузить, но после Информационного окна сервер работает в принципе он его не выключает

_Originally posted by @ilyarudziak in https://github.com/WizaXxX/docker_fresh/issues/14#issuecomment-650173344_

**Comment by WizaXxX** [comment]
Теперь проблему понял, надо подумать как тут лучше сделать.

> А может мне 2 раза запустить start.py ? там при первом запуске он ругается на лицензии когда пытается базы загрузить, но после Информационного окна сервер работает в принципе он его не выключает

Не поможет, т.к. при запуске скрипта с параметром -new происходит настройка и связка всех компонентов. И при повторном запуске с этим же ключом каталог workdir полностью удаляется.

А разве ТНФ распространяется на серверные лицензии? Мне всегда казалось что серверные лицензии по сети не шарятся ни как.

**Comment by ilyarudziak** [comment]
Программные серверные и клиентские  "шарятся".  На счет usb лично не проверял. 
Я попробовал сервер лицензирования в кластер добавить, он добавился он так как у меня адрес подсеть 192.168.0...а в docker0 172.17.0.2/16 он просто не видит ничего. 

то есть я с хоста вижу  сервер докера, а вот из самого докера уже мой сервер лицензирования никак

**Comment by WizaXxX** [comment]
Это очень странно, должны видеть. 
А что показывает команда ping натравленная на адрес вашего сервера? Запустить надо из контейнера, что бы зайти в контейнер воспользуйтесь командой `docker exec -it srv.ИмяСтенда.1cfresh.dev bash`

**Comment by ilyarudziak** [comment]
Да, видит кстати сервер. Но странно не запускает рабочий процесс, хотя в сети на обычном сервере, сервер лицензирования добавляется и запускается вроде без проблем.
[https://dropmefiles.com/MQcr4](url)

**Comment by WizaXxX** [comment]
Получается нужно сделать возможность указать список ТНФ. И он должен применятся сразу после поднятия контейнеров но до начала создания ИБ.

**Comment by ilyarudziak** [comment]
Может будет полезно.
https://its.1c.ru/db/freshadep/content/90/1/issogl1_2.3.4_%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B_%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BB%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D0%B9_1%D1%81_%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D1%8F_8

Там автоматическая установка сервера, и есть как раз пример по нашей ситуации

**Comment by ilyarudziak** [comment]
Добрый день. Удалось подключить сервер лицензирования (быстро добавил его в консоль когда сервер только поднялся), а как долго должны базы грузится? 
![2020-06-30_11-46-16](https://user-images.githubusercontent.com/18754334/86105158-a94ee680-bac7-11ea-9993-b5802b59ce96.png)
минут 10 уже готовит, думаю что моя схема не прошла)

**Comment by WizaXxX** [comment]
Все зависит от железа, у меня первоначальный запуск занимает минут 7.

**Comment by ilyarudziak** [comment]
Понял,спасибо. Словил такую штуку 

![2020-06-30_12-51-14](https://user-images.githubusercontent.com/18754334/86112249-66ddd780-bad0-11ea-8893-adfca3688312.png)

Единственное отличие это в в папки с дистрибутивами новые версии платформы поместил. Но тут с что-то с доступом думаю

**Comment by WizaXxX** [comment]
а в этот момент данной ошибки, контейнер db был запущен? Такое ощущение что он не запущен, может упал по какой то причине?

**Comment by WizaXxX** [comment]
Переехал сюда https://github.com/1C-Company/docker_fresh/issues/3
