### ISSUE TITLE
Активация программных лицензий

### ISSUE THREAD

**Issue by TeamUaS** [WizaXxX/docker_fresh#18]
Добрый вечер! пытаюсь активировать лицензию пользовательскую но получаю сообщение

admins@gh:~/docker_fresh$ sudo docker run --rm -it \
> -v /home/admins/docker_fresh/licenses_1c:/var/1C/licenses \
> fresh/core \ bash -l -c 'ring license activate --company "___________и" --email "____@___.ru" --country "Russia" --zip-code "640000" --town "_____" --street "_____" --house "___" --serial "_____________" --pin "___________" --send-statistics "false"'
**/entrypoint.sh: line 60: exec:  bash: not found
failed to resize tty, using default size**
В чем может быть причина ?
Спасибо!

**Comment by WizaXxX** [comment]
Добрый. Извините, проблема в `-it`. Если уберёте этот параметр должно завестись:)

**Comment by TeamUaS** [comment]
Добрый день! Создание нового стенда

admins@gh:~/docker_fresh$ sudo python3 start.py -new -h zzz
Fresh is starting at 2020-07-28 16:37:27.106485
**start.py:94: DeprecationWarning: isAlive() is deprecated, use is_alive() instead
  while progress_thread.isAlive():** -
Down all conteiners ... done 
host name is zzz.1cfresh.dev
Set full hostname ... done 
Renew wordir ... done 
Get configuration data ... done 
Renew nginx files ... done 
Renew docker-compose file ... done 
Renew other-files ... done 
Delete volumes ... done 
Creating network "workdir_default" with the default driver
Creating volume "workdir_1c_pg_data" with default driver
Creating volume "workdir_1c_pg_socket" with default driver
Creating db.zzz.1cfresh.dev  ... done
Creating ras.zzz.1cfresh.dev ... done
Creating srv.zzz.1cfresh.dev ... done
Creating web.zzz.1cfresh.dev  ... done
Creating gate.zzz.1cfresh.dev ... done
Waiting for postgres ... done 
Publish services ... done 
**Prepare all bases ......** - уже на этой задаче висит несколько часов 
из за чего так может долго выполняться 
Спасибо

**Comment by TeamUaS** [comment]
Добрый вечер ! Обошел таким образом вводил частями 
sudo docker run --rm -it \
**>**-v /home/admins/docker_fresh/licenses_1c:/var/1C/licenses  \
**>**fresh/core \
**>**bash -l -c 'ring license activate --company "и" --email "_@.ru" --country "Russia" --zip-code "640000" --town "" --street "" --house "" --serial "___________" --pin "___________" --send-statistics "false"'
Активация выполнена
