### ISSUE TITLE
При работе из Linux нужно добавить в инструкцию, что текущего пользователя нужно добавить в группу, которой доступно использование docker

### ISSUE THREAD

**Issue by Tedman** [WizaXxX/docker_fresh#4]
ted@ted-vm:~/docker_fresh$ docker ps -a
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied

**Comment by SkyCorvette** [comment]
If you would like to use Docker as a non-root user, you should now consider adding your user to the “docker” group with something like:

  sudo usermod -aG docker your-user
